config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :employees

  resources :admins
  get "admins/new"

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  
  
 
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  

  
  match '/signup' => 'admins#new'
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy'
  match '/help'   =>  'static_pages#help'
  match '/home'  =>'static_pages#home'
  match '/about'  => 'static_pages#about'
  match '/contact' => 'static_pages#contact'
  
  
  

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :password, :username ,:remember_token
  before_save :create_remember_token
  
  
  
  
  
   class << self
    def authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end
  
   private

    def create_remember_token
      #self.email = email.don
    end
    
    
  
  
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :address, :bank_acc_no, :date_of_birth, :date_of_joining, :date_of_relieve, :designation, :email_id, :emp_id, :first_name, :gender, :grossCTC, :last_name, :pan_number, :phone_number, :status
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :signed_in_user
  
  
  def new
  end
  
  
  def signed_in_user
      redirect_to signin_path, :notice=> "Access Deniend Please Login ." unless signed_in?
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper 
  include ApplicationHelper
  protect_from_forgery
  helper :all
  helper_method :authenticate, :current_user
  
   def handle_unverified_request
    sign_out
    super
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, :notice => 'Employee was successfully created.' }
        format.json { render :json => @employee, :status => :created, :location => @employee }
      else
        format.html { render :action => "new" }
        format.json { render :json => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, :notice => 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  include SessionsHelper 
  include ApplicationHelper
  protect_from_forgery
  

  def new
  end

  def create
  username=params[:session][:username]
  password=params[:session][:password]
  admin = Admin.where(:username=> "#{username}" , :password => "#{password}")
    if admin.any?
      sign_in(admin)
      flash[:success] = "Welcome to the India Payroll App!"
      render "admins/index"
    else
      flash.now[:error] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to signin_path
    flash[:success] ="succefully logout the PayRoll Application"
  end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title)                          # Method definition
    base_title = "INDIA PAYROLL"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{base_title} | #{page_title}"                 # String interpolation
    end
  end
  
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 
 
 def sign_in(user)
    cookies.permanent[:remember_token] = user.id
    self.current_user = user
  end
    
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
     @current_user ||= Admin.find_by_remember_token(cookies[:remember_token])
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end


  def current_user?(user)
    user == current_user
  end
  
  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = admin
  end
  
  private

    def user_from_remember_token
      Admin.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end


    def clear_return_to
      session[:return_to] = nil
    end 
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/new.html.erb
<h1>Admins#new</h1>
<p>Find me in app/views/admins/new.html.erb</p>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :emp_id %><br />
    <%= f.text_field :emp_id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :email_id %><br />
    <%= f.text_field :email_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :pan_number %><br />
    <%= f.number_field :pan_number %>
  </div>
  <div class="field">
    <%= f.label :bank_acc_no %><br />
    <%= f.number_field :bank_acc_no %>
  </div>
  <div class="field">
    <%= f.label :designation %><br />
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :grossCTC %><br />
    <%= f.text_field :grossCTC %>
  </div>
  <div class="field">
    <%= f.label :date_of_joining %><br />
    <%= f.date_select :date_of_joining %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :date_of_relieve %><br />
    <%= f.date_select :date_of_relieve %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Emp</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Gender</th>
    <th>Email</th>
    <th>Address</th>
    <th>Phone number</th>
    <th>Pan number</th>
    <th>Bank acc no</th>
    <th>Designation</th>
    <th>Grossctc</th>
    <th>Date of joining</th>
    <th>Date of birth</th>
    <th>Date of relieve</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.emp_id %></td>
    <td><%= employee.first_name %></td>
    <td><%= employee.last_name %></td>
    <td><%= employee.gender %></td>
    <td><%= employee.email_id %></td>
    <td><%= employee.address %></td>
    <td><%= employee.phone_number %></td>
    <td><%= employee.pan_number %></td>
    <td><%= employee.bank_acc_no %></td>
    <td><%= employee.designation %></td>
    <td><%= employee.grossCTC %></td>
    <td><%= employee.date_of_joining %></td>
    <td><%= employee.date_of_birth %></td>
    <td><%= employee.date_of_relieve %></td>
    <td><%= employee.status %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Emp:</b>
  <%= @employee.emp_id %>
</p>

<p>
  <b>First name:</b>
  <%= @employee.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @employee.last_name %>
</p>

<p>
  <b>Gender:</b>
  <%= @employee.gender %>
</p>

<p>
  <b>Email:</b>
  <%= @employee.email_id %>
</p>

<p>
  <b>Address:</b>
  <%= @employee.address %>
</p>

<p>
  <b>Phone number:</b>
  <%= @employee.phone_number %>
</p>

<p>
  <b>Pan number:</b>
  <%= @employee.pan_number %>
</p>

<p>
  <b>Bank acc no:</b>
  <%= @employee.bank_acc_no %>
</p>

<p>
  <b>Designation:</b>
  <%= @employee.designation %>
</p>

<p>
  <b>Grossctc:</b>
  <%= @employee.grossCTC %>
</p>

<p>
  <b>Date of joining:</b>
  <%= @employee.date_of_joining %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @employee.date_of_birth %>
</p>

<p>
  <b>Date of relieve:</b>
  <%= @employee.date_of_relieve %>
</p>

<p>
  <b>Status:</b>
  <%= @employee.status %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    India Payroll
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'about_path' %></li>
      <li><%= link_to "Contact", 'contact_path' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag('/images/wales.png'),"www.google.com" , :id=> "logo" %>
      <nav>
        <ul class="nav pull-right">
        	<% if signed_in? %>
          <li><%= link_to "Home", "#" %></li>
          <li><%= link_to "considarated pay", "#" %></li>
          
            <li><%= link_to "Run Payroll", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Employee <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Add Employee", new_employee_path %></li>
                <li><%= link_to "Employee List", '#' %></li>
                <li><%= link_to "Bulk Edit of Emp Pay", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, :method=> "delete" %>
                </li>
              </ul>
            </li>
            <%else%>
            <li><%= link_to "Sign in", signin_path %></li>
            <%end%>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media=> "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
      <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    
      
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>India Payroll</h1>

  <h2>
    This is INdia Payroll Application
  </h2>

  <%= link_to "Click Here To signin ", 'signin', :class=> "btn btn-large btn-primary" %>
</div>